name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            clang \
            cmake \
            ninja-build

      - name: Configure
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Package
        run: |
          mkdir release

          cp build/bin/gecko release/
          cp build/bin/gpm release/

          tar -czf igecko-linux.tar.gz release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            igecko-linux.tar.gz
